### ISSUE TITLE
DPU - Add support for OVS and representors

### ISSUE THREAD

**Issue by MrBr-github** [MrBr-github/lshca#26]
https://docs.nvidia.com/networking/display/BlueFieldDPUOSLatest/Kernel+Representors+Model

**Comment by MrBr-github** [comment]
OVS vsctl show to YAML conversion
```
# ovs-vsctl show | sed 's/\([^ ]\+\) /\1: /g;s/^\([a-f0-9-]\+\)$/\1:/;s/::/:/g'
32a83c18-94bc-48f1-af19-9ccf9f4e727b:
    Bridge: ovsbr2
        Port: en3f1pf1sf0
            Interface: en3f1pf1sf0
        Port: ovsbr2
            Interface: ovsbr2
                type: internal
        Port: pf1hpf
            Interface: pf1hpf
        Port: p1
            Interface: p1
    Bridge: ovsbr1
        Port: pf0hpf
            Interface: pf0hpf
        Port: en3f0pf0sf0
            Interface: en3f0pf0sf0
        Port: p0
            Interface: p0
        Port: ovsbr1
            Interface: ovsbr1
                type: internal
    ovs_version: "2.15.1-d246dab"
```
